:q[settings]
timeout = 600

[[relaychain]]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

[[parachains]]
id = 1000
cumulus_based = true
chain = "canvas-local"
command = "canvas-node"
args = ["--dev"]

  [[parachains.collators]]
  name = "collator01"

